version: '3.8'

services:
  # 1. Contenedor de la Base de Datos Global
  mysql-db:
    build:
      context: ./Db  # Apunta a la carpeta donde está tu Dockerfile de MySQL y el init.sql
    container_name: sanos_salvos_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: stefy
    volumes:
      - mysql_data:/var/lib/mysql # Guarda los datos para que no se borren si apagas el contenedor
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pstefy"]
      timeout: 20s
      retries: 10

  # 2. Contenedor del Microservicio de Usuarios
  usuarios-api:
    build:
      context: ./Backend/usuarios # Apunta a la carpeta de tu API
    container_name: api-usuarios
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy # Espera a que MySQL esté 100% listo antes de encender Spring Boot
    environment:
      - DB_HOST=mysql-db # ¡Magia de Docker! Usa el nombre del contenedor como IP
      - DB_PORT=3306
      - DB_NAME=usuariosdb
      - DB_USER=root
      - DB_PASSWORD=stefy
      - JWT_SECRET_KEY=UHJveWVjdG9HcnVwb0NTYW5vc1lTYWx2b3NTZWNyZXRLZXkyMDI2ISE=
      - JWT_EXPIRATION_MS=86400000

  # 3. Contenedor del Microservicio de Mascotas (¡NUEVO!)
  mascotas-api:
    build:
      context: ./Backend/mascotas # Asegúrate de que esta ruta apunte a la carpeta de mascotas
    container_name: api-mascotas
    ports:
      - "8081:8081" # Usamos el puerto 8081 para no chocar con usuarios
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8081
      - DB_HOST=mysql-db 
      - DB_PORT=3306
      - DB_NAME=mascotasdb
      - DB_USER=root
      - DB_PASSWORD=stefy
      # Pasamos la misma clave secreta para que pueda validar los tokens que generó el ms-usuarios
      - JWT_SECRET=UHJveWVjdG9HcnVwb0NTYW5vc1lTYWx2b3NTZWNyZXRLZXkyMDI2ISE=
      - GEOLOCALIZACION_API_URL=http://api-geolocalizacion:8082
    volumes:
      - ./uploads/imagenes:/app/uploads/imagenes # Montamos el código para desarrollo en caliente

# 4. Microservicio Geolocalización (¡NUEVO!)
  geolocalizacion-api:
    build:
      context: ./Backend/geolocalizacion # Ruta a la carpeta de este microservicio
    container_name: api-geolocalizacion
    ports:
      - "8082:8082"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SERVER_PORT=8082
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=geolocalizaciondb
      - DB_USER=root
      - DB_PASSWORD=stefy
      - JWT_SECRET_KEY=UHJveWVjdG9HcnVwb0NTYW5vc1lTYWx2b3NTZWNyZXRLZXkyMDI2ISE= # <- ¡AÑADIR ESTO!
# 5. Microservicio Motor de Coincidencias (¡NUEVO!)
  coincidencias-api:
    build:
      context: ./Backend/motor_coincidencias # Asegúrate de que el nombre de la carpeta coincida
    container_name: api-coincidencias
    ports:
      - "8083:8083" # El puerto que definiste en tu application.properties
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=coincidenciasdb
      - DB_USER=root
      - DB_PASSWORD=stefy
      - JWT_SECRET_KEY=UHJveWVjdG9HcnVwb0NTYW5vc1lTYWx2b3NTZWNyZXRLZXkyMDI2ISE= # Adaptarlo a JWT_SECRET o JWT_SECRET_KEY según tu application.properties
      - MASCOTAS_API_URL=http://api-mascotas:8081
      - GEOLOCALIZACION_API_URL=http://api-geolocalizacion:8082
volumes:
  mysql_data: