version: '3.8'

services:
  # 1. Contenedor del Microservicio de Usuarios
  usuarios-api:
    build:
      context: ./Contenedor_Usuarios 
    container_name: api-usuarios
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET}
      - JWT_EXPIRATION_MS=86400000
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  # 2. Contenedor del Microservicio de Mascotas
  mascotas-api:
    build:
      context: ./Contenedor_Mascotas 
    container_name: api-mascotas
    ports:
      - "8081:8081" 
    environment:
      - SERVER_PORT=8081
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GEOLOCALIZACION_API_URL=http://api-geolocalizacion:8082
    volumes:
      - ./uploads/imagenes:/app/uploads/imagenes 

  # 3. Microservicio Geolocalización
  geolocalizacion-api:
    build:
      context: ./Contenedor_Geolocalizacion 
    container_name: api-geolocalizacion
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET} 

  # 4. Microservicio Motor de Coincidencias
  coincidencias-api:
    build:
      context: ./Contenedor_Coincidencias 
    container_name: api-coincidencias
    ports:
      - "8083:8083" 
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET}
      - MASCOTAS_API_URL=http://api-mascotas:8081
      - GEOLOCALIZACION_API_URL=http://api-geolocalizacion:8082